### ISSUE TITLE
support for `in`

### ISSUE THREAD

**Issue by afeld** [aequitas/concourse-http-api-resource#1]
I'm interested in using this Resource for fetching data to trigger pipelines...are you working on the `in` support already? If not, would you be open to a pull request for it? Thanks!

**Comment by aequitas** [comment]
Sure, be glad to include it, I had no need for a check/in action so did not implement anything yet. 

Though maybe the use case could be a better fit for the `http` resource: https://github.com/cromega/http-resource as that one is geared more towards files and I named/described mine to specifically targets API's (which doesn't say it shouldn't handle files).

**Comment by aequitas** [comment]
@afeld i started working on: https://github.com/aequitas/concourse-http-resource I think it's a better place to implement the feature you requested. Feel free to open an pr with a test for your case and/or implementation
