### ISSUE TITLE
Require image for ARM64 architecture

### ISSUE THREAD

**Issue by odidev** [aequitas/concourse-http-api-resource#16]
Hi team,

I am trying to use **concourse-http-api-resource** on ARM64 architecture but it seems the arm64 tag is not available in Docker Hub.

I have tried to build the image using the command docker build -t <image_name > .  on both amd64 and arm64 platforms but is failing for amd64 as well.

I made some changes in order to resolve the errors. After doing the below changes, the image was successfully built on both platforms.

**Commit Link** - https://github.com/odidev/concourse-http-api-resource/commit/6dd1216955708f7642dbcbe5874d0044a4173e18

Do you have any plans on releasing arm64 images?

May I know how the amd64 image is getting published on Dockerhub?

It will be very helpful if the image is released with ARM64 support. To start with can I get suggestions on which CI you are using to push the image to Dockerhub.

**Comment by aequitas** [comment]
I think it used Docker's build system in the past, but due to Docker requiring access to private repo's that was removed a while back. I'll check if I can add automated builds using Github Actions.

**Comment by aequitas** [comment]
I've pushed a new multi-arch build to the Docker Hub https://hub.docker.com/r/aequitas/http-api-resource/tags?page=1&ordering=last_updated
