### ISSUE TITLE
Recursive variable interpolation needs a case for lists

### ISSUE THREAD

**Issue by ericroy** [aequitas/concourse-http-api-resource#2]
Currently, recursive string interpolation doesn't recurse into lists.  It should be pretty easy to add a case to handle this here:
https://github.com/aequitas/concourse-http-api-resource/blob/master/assets/resource.py#L103

eg:

```
for k, v in data.items():
    if isinstance(k, str):
        k = k.format(**values)
    if isinstance(v, str):
        v = v.format(**values)
    elif isinstance(v, dict):
        v = self._interpolate(v, values)
    elif isinstance(v, list):
        v = [self._interpolate(o, values) for o in v]
```

**Comment by aequitas** [comment]
sorry for the late reply, fixed in next release.
