### ISSUE TITLE
Can you add how to include this resource in the pipeline manifest

### ISSUE THREAD

**Issue by ghost** [aequitas/concourse-http-api-resource#4]
Often, custom resources such as http-api-resource need to be included under resource_type section of the pipeline. Can you please add information in your README.md on how to include this resource in the pipeline. Thanks. 

Example

---
resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

**Comment by aequitas** [comment]
fixed in next release
