### ISSUE TITLE
json.dumps need `ensure_ascii=False `.

### ISSUE THREAD

**Issue by masaki-takano** [aequitas/concourse-http-api-resource#9]
It is a very good tool.

https://github.com/aequitas/concourse-http-api-resource/blob/a4400a547ff11110c78b4446161c7ca6cd25e791/assets/resource.py#L33

I think json.dumps need `ensure_ascii=False `.
if not Japanese characters etc. garbled.

```
dict = {"hello": "日本語"}
text = json.dumps(dict, ensure_ascii=False)
```

Thank you

**Comment by aequitas** [comment]
Fixed in #10
